# Generated by Django 4.2.2 on 2023-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum_user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
