# Generated by Django 4.2.2 on 2023-07-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_spectrum_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum_user',
            name='profile_pic',
            field=models.ImageField(default='spec-library/spec-library/frontend/public/User Icon.png', upload_to=''),
        ),
    ]
