# Generated by Django 4.2.2 on 2023-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_spectrum_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum_user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
