# Generated by Django 4.2.2 on 2023-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_spectrum_user_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Not Entered')], default=''),
        ),
    ]
