# Generated by Django 4.2.2 on 2023-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_spectrum_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum_user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('tutor', 'Tutor')], default='student'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
